// <auto-generated />
using System;
using BurglarBuster.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurglarBuster.Infrastructure.Migrations
{
    [DbContext(typeof(BurglarBusterDbContext))]
    [Migration("20260917071546_AddInvestigations")]
    partial class AddInvestigations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BurglarBuster.Core.Entities.CaseReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("CaseReferences");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.Investigation", b =>
                {
                    b.Property<string>("InvestigationId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelDeploymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelTurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedInformationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TerminationReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolCallCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestigationId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.InvestigationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestigationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("PersonId");

                    b.ToTable("InvestigationCandidates");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleNames")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("FamilyName");

                    b.HasIndex("FamilyName", "GivenName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PersonAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Locality");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAddresses");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PersonAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RecordedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAliases");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PhysicalDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApproximateHeightCm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DistinguishingMarks")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColour")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColour")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhysicalDescriptions");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.CaseReference", b =>
                {
                    b.HasOne("BurglarBuster.Core.Entities.Person", "Person")
                        .WithMany("CaseReferences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.InvestigationCandidate", b =>
                {
                    b.HasOne("BurglarBuster.Core.Entities.Investigation", "Investigation")
                        .WithMany("Candidates")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PersonAddress", b =>
                {
                    b.HasOne("BurglarBuster.Core.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PersonAlias", b =>
                {
                    b.HasOne("BurglarBuster.Core.Entities.Person", "Person")
                        .WithMany("Aliases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.PhysicalDescription", b =>
                {
                    b.HasOne("BurglarBuster.Core.Entities.Person", "Person")
                        .WithMany("PhysicalDescriptions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.Investigation", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("BurglarBuster.Core.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Aliases");

                    b.Navigation("CaseReferences");

                    b.Navigation("PhysicalDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
